version: '3.9'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    working_dir: /client
    volumes: 
      - ./client/:/client/
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  api:
    container_name: api
    build: ./api
    ports:
      - 3001:3001
    working_dir: /api
    volumes: 
      - ./api/:/api/
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=3001
      - JWT_SECRET=segredobemguardado
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  adminer:  ## O adminer está aqui apenas para visualização da estrutura do banco
    image: adminer
    restart: always
    ports:
      - 8080:8080